apiVersion: apps/v1
kind: Deployment
metadata:
  name: primuslearnings
  labels:
    app: primuslearnings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primuslearnings
  template:
    metadata:
      labels:
        app: primuslearnings
    spec:
      containers:
        - name: primuslearnings
          image: 499156924743.dkr.ecr.us-east-2.amazonaws.com/primuslearning:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8181
